# Generated by Django 4.1.2 on 2022-11-03 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, blank = False, max_length=30)),
                ('description', models.CharField(unique = False, blank = True,max_length=120)),
                ('quantity', models.PositiveIntegerField(unique = False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
