# Generated by Django 4.1.2 on 2022-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_rename_bio_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='No current description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
